import tseslint from "typescript-eslint";

// Deliberately conservative.
//
// This repository had no linter, so the goal of the first configuration is to
// catch real defects without forcing a mass rewrite. It therefore enables only
// correctness rules and no stylistic ones: adopting Prettier or a formatting
// rule set would rewrite roughly 64k lines in a single commit and bury every
// real change alongside it. Tighten this incrementally, one rule at a time.
//
// `.astro` files are out of scope because they need a dedicated parser; lint
// the TypeScript and TSX inside them via the components they import.
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      ".microfeed/**",
      "docs/.astro/**",
      "docs/node_modules/**",
      "packages/*/dist/**",
      "src/worker-configuration.d.ts",
      "themes/*/assets/**",
      // Generated by the shadcn CLI. Editing it makes the next regeneration
      // produce a diff, so it is excluded rather than fixed.
      "src/components/ui/**",
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      ecmaVersion: "latest",
      parser: tseslint.parser,
      sourceType: "module",
    },
    plugins: {"@typescript-eslint": tseslint.plugin},
    rules: {
      // Comparisons and control flow
      "eqeqeq": ["error", "smart"],
      "no-constant-condition": ["error", {checkLoops: false}],
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-empty": ["error", {allowEmptyCatch: true}],
      "no-fallthrough": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-unreachable": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-private-class-members": "error",
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "use-isnan": "error",
      "valid-typeof": "error",

      // Deliberately OFF: this rule cannot tell a sequential await from a
      // concurrent one, so it fires on every `obj.field = await ...` after the
      // object was read. All 29 hits in this repository are that pattern
      // (`context.locals.x`, `config.x`, `journal.stage`), which is why it is
      // not enabled rather than "fixed".
      "require-atomic-updates": "off",

      // Dead or surprising code
      "no-debugger": "error",
      "no-var": "error",
      // ignoreReadBeforeAssign: a `let` that is read before its single later
      // assignment (a timer handle, for example) cannot become `const` without
      // reordering the code, so it is not reported.
      "prefer-const": ["error", {ignoreReadBeforeAssign: true}],

      // TypeScript-specific correctness
      "@typescript-eslint/no-duplicate-enum-values": "error",
      "@typescript-eslint/no-misused-new": "error",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/no-unsafe-function-type": "error",
    },
  },
);
